### ISSUE TITLE
SQL Dump incomplete?

### ISSUE THREAD

**Issue by adelnobel** [TarteelAI/quranic-universal-library#186]
Salam,

I'm trying to use the sql dump provided on this github, the verses table seems to be incomplete.

Running the query on the imported database

```
        SELECT count(*)
        FROM quran.verses
```

returns 1923 

while I can see 6326 entries on https://qul.tarteel.ai/admin/verses

cc @naveed-ahmad

**Comment by naveed-ahmad** [comment]
waAlakim o salam, this is intentional.  The dump has first 20 ayah of all surahs, all words for these selected ayahs all word translations, two translations for each language etc. This dump is enough if you want to develop an feature for QUL. 

But if you need data for developing your app, you can download it from [resources](https://qul.tarteel.ai/resources) page. Or if you just want to browse through the available resources, you can login and use [admin](https://qul.tarteel.ai/admin) section of the site. 

If you can't find the resource you're looking for, or need data in certain format please open another issue. 

I hope this answers your question.
